# Use the official Node.js runtime as the base image
FROM node:18-alpine

# Set the working directory inside the container
WORKDIR /usr/src/app

# Copy dependency files first
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application files
COPY . .

# Expose the port (optional; depends on your app's configuration)
EXPOSE 3000

# Start the application
CMD ["npm", "run", "start:dev"]

# FROM node:18-alpine

# WORKDIR /usr/src/app
# COPY package*.json ./
# COPY nodemon.json ./

# CMD npm config set cache-min 9999999 \
#     && npm install \
#     && npm run start:dev